<Workspace Version="0.8.0.950" X="40.9097490058157" Y="48.4792103161151" zoom="0.610282075168554" Name="Home" RunType="Manual" RunPeriod="100" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSIronPythonNode.PythonNode guid="78798a42-e6fb-4f4c-97a1-3b6fb100541e" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="287.36871836619" y="-47.0255463665406" isVisible="false" isUpstreamVisible="true" lacing="Disabled" inputcount="5">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import sys
sys.path.append(r'C:\Program Files (x86)\IronPython 2.7\Lib')

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

import math
import random

PI = 3.14159
out_points = []
R = float(IN[0])
r = float(IN[1])
p = float(IN[2])
step = float(IN[3])
epicycloid = bool(IN[4])


def jitter():
	r = random.random() - 0.5
	return r * 0.00002

def seq(start, stop, step=1):
    n = int(round((stop - start)/step))
    if n &gt; 1:
        return([start + step*i for i in range(n+1)])
    else:
        return([])

def hypocycloidPoint(R, r, p, t):
	a = R - r
	b = r/R * t
	c = (1 - r/R) * t
	x = a * math.cos(b) - p * math.cos(c)
	y = a * math.sin(b) + p * math.sin(c)
	return Point.ByCoordinates(x, y)
	
	
def epicycloidPoint(R, r, p, t):
	a = R + r
	b = r/R * t
	c = (1 + r/R) * t
	x = a * math.cos(b) - p * math.cos(c)
	y = a * math.sin(b) + p * math.sin(c)
	return Point.ByCoordinates(x, y)

def hypocycloidLine(R, r, p, t1, t2):
	return Line.ByStartPointEndPoint(hypocycloidPoint(R, r, p, t1), hypocycloidPoint(R, r, p, t2))


def epicycloidLine(R, r, p, t1, t2):
	return Line.ByStartPointEndPoint(epicycloidPoint(R, r, p, t1), epicycloidPoint(R, r, p, t2))

for t in seq(0 * PI, 36 * PI, step):
	#out_points.Add(epicycloidPoint(R, r, p, t) if epicycloid else hypocycloidPoint(R, r, p, t))
	out_points.Add(epicycloidLine(R, r, p, t, t + step) if epicycloid else hypocycloidLine(R, r, p, t, t + step))
	
#Assign your output to the OUT variable
OUT = out_points</Script>
    </DSIronPythonNode.PythonNode>
    <DSCoreNodesUI.Input.DoubleSlider guid="ce4d55e7-5cc5-49ad-9f46-a7ae9e6deeb9" type="DSCoreNodesUI.Input.DoubleSlider" nickname="Outer ring radius" x="-41.6311602238696" y="-47.4297781563021" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double>57.98</System.Double>
      <Range min="1" max="500" step="0.01" />
    </DSCoreNodesUI.Input.DoubleSlider>
    <DSCoreNodesUI.Input.DoubleSlider guid="7e844350-4e3a-4a8f-a794-3813d252d06a" type="DSCoreNodesUI.Input.DoubleSlider" nickname="Gear radius" x="-43.0880485826062" y="18.3755740362232" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double>72.13</System.Double>
      <Range min="1" max="500" step="0.01" />
    </DSCoreNodesUI.Input.DoubleSlider>
    <DSCoreNodesUI.Input.DoubleSlider guid="ce204e6c-e33e-411d-98d3-e0eb27447c7d" type="DSCoreNodesUI.Input.DoubleSlider" nickname="Pen offset" x="-42.7055084301877" y="81.6449176837263" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double>108.92</System.Double>
      <Range min="0" max="250" step="0.01" />
    </DSCoreNodesUI.Input.DoubleSlider>
    <DSCoreNodesUI.Input.DoubleSlider guid="0a494160-87d9-491a-857c-73c25a34e048" type="DSCoreNodesUI.Input.DoubleSlider" nickname="Step size" x="-42.8399340187427" y="143.632149968808" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double>0.046</System.Double>
      <Range min="0.001" max="0.2" step="0.001" />
    </DSCoreNodesUI.Input.DoubleSlider>
    <DSCoreNodesUI.BoolSelector guid="24da7bab-17a9-4b6a-9389-d36c53377414" type="DSCoreNodesUI.BoolSelector" nickname="Epicycloid?" x="287.48813769587" y="146.756474517281" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Boolean>True</System.Boolean>
    </DSCoreNodesUI.BoolSelector>
    <DSIronPythonNode.PythonNode guid="7b786d81-a0e0-4d68-8b2e-e00ef4df1d6a" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="429.521455490803" y="-47.6296044168546" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import sys
sys.path.append(r'C:\Program Files (x86)\IronPython 2.7\Lib')

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

import math
import random

PI = 3.14159
out_polygons = []
lines = IN[0]

for line in lines:
	d1 = math.sqrt(math.pow(line.StartPoint.X, 2) + math.pow(line.StartPoint.Y, 2)) * 0.05
	d2 = math.sqrt(math.pow(line.EndPoint.X, 2) + math.pow(line.EndPoint.Y, 2)) * 0.05
	n = Vector.ByTwoPoints(line.StartPoint, line.EndPoint)
	v1 = n.Cross(Vector.ByCoordinates(0, 0, 1)).Normalized().Scale(d1)
	v2 = n.Cross(Vector.ByCoordinates(0, 0, 1)).Normalized().Scale(d2)

	pts = []
	pts.Add(line.StartPoint.Add(v1))
	pts.Add(line.StartPoint.Subtract(v1))
	pts.Add(line.EndPoint.Subtract(v2))
	pts.Add(line.EndPoint.Add(v2))
	out_polygons.Add(Polygon.ByPoints(pts))

	
#Assign your output to the OUT variable
OUT = out_polygons</Script>
    </DSIronPythonNode.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="78798a42-e6fb-4f4c-97a1-3b6fb100541e" start_index="0" end="7b786d81-a0e0-4d68-8b2e-e00ef4df1d6a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ce4d55e7-5cc5-49ad-9f46-a7ae9e6deeb9" start_index="0" end="78798a42-e6fb-4f4c-97a1-3b6fb100541e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7e844350-4e3a-4a8f-a794-3813d252d06a" start_index="0" end="78798a42-e6fb-4f4c-97a1-3b6fb100541e" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="ce204e6c-e33e-411d-98d3-e0eb27447c7d" start_index="0" end="78798a42-e6fb-4f4c-97a1-3b6fb100541e" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="0a494160-87d9-491a-857c-73c25a34e048" start_index="0" end="78798a42-e6fb-4f4c-97a1-3b6fb100541e" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="24da7bab-17a9-4b6a-9389-d36c53377414" start_index="0" end="78798a42-e6fb-4f4c-97a1-3b6fb100541e" end_index="4" portType="0" />
  </Connectors>
  <Notes />
</Workspace>